### ISSUE TITLE
Binary crashing with gitsigns

### ISSUE THREAD

**Issue by Coder2195Text** [lewis6991/gitsigns.nvim#763] opened 2023-03-05 21:26 UTC
### Description

Binary files do not work well with gitsigns

How do I know? 

I have been experiencing this for a while now. It seems to only occur inside git repo binaries, and nvim --clean in git repo binaries didn't trigger crash

Knowing this, I tracked it down to this one plugin

I had a feeling it was something with git diff highlighting and I was right,

[Screencast from 03-05-2023 04:14:36 PM.webm](https://user-images.githubusercontent.com/63069499/222986457-6cc0dc3f-ef74-4aaa-986c-e50d17d8e138.webm)

They crash when its enabled.

### Neovim version

NVIM v0.9.0-dev-1115+g446c353a5

### Operating system and version

Ubuntu 22.04

### Expected behavior

Work without crashing

### Actual behavior

Video at the top

### Minimal config

Since I rely on an astronvim v3 distro, just use https://github.com/astronvim/astronvim/tree/nightly

### Steps to reproduce

Clone https://github.com/astronvim/astronvim/tree/nightly into ~/.config/nvim

Open a binary file that is part of a git repo

It should crash

**Comment by lewis6991** [comment] 2023-03-05 21:34
Can you confirm if you have `linematch` set in `diffopt`?

**Comment by Coder2195Text** [comment] 2023-03-05 22:24
> Can you confirm if you have `linematch` set in `diffopt`?

![image](https://user-images.githubusercontent.com/63069499/222989323-c13fb7a6-d95a-4b36-8c06-b77f1e84f69a.png)

**Comment by lewis6991** [comment] 2023-03-05 22:26
This is an upstream issue. Duplicate of #758

**Comment by lewis6991** [comment] 2023-03-06 16:10
Should bed fixed with https://github.com/neovim/neovim/pull/22552

**Closed by lewis6991** 2023-03-06 16:10 UTC
Labels: bug, upstream issue
