### ISSUE TITLE
`preview_hunk` closes one of the windows open in a vertical split

### ISSUE THREAD

**Issue by heygarrett** [lewis6991/gitsigns.nvim#629] opened 2022-09-15 01:05 UTC
### Description

When I have two windows open in a vertical split, running `lua require("gitsigns").preview_hunk()` closes the window on the left, leaving me with only the window that was open on the right.

### Neovim version

```
NVIM v0.8.0-dev-2548-gbf6de51f5-dirty
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by garrett@Garretts-MacBook-Pro.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/HEAD-bf6de51_1/share/nvim"

Run :checkhealth for more info
```

### Operating system and version

macOS 12.5.1

### Expected behavior

Both windows in the split would remain open and the hunk preview window would be displayed.

### Actual behavior

The window on the left is closed, and the hunk preview window appears in the remaining window, regardless of which window I ran `preview_hunk` from.

### Minimal config

```Lua
vim.o.packpath = "/tmp/nvim/site"

local plugins = {
	gitsigns = "https://github.com/lewis6991/gitsigns.nvim",
}

for name, url in pairs(plugins) do
	local install_path = "/tmp/nvim/site/pack/test/start/" .. name
	if vim.fn.isdirectory(install_path) == 0 then
		vim.fn.system({ "git", "clone", "--depth=1", url, install_path })
	end
end

require("gitsigns").setup({
	debug_mode = true,
})

vim.opt.signcolumn = "yes:1"
```

### Steps to reproduce

1. `nvim --clean -u minimal.lua`  
2. Open two different files in a vertical split (eg, `:vs | find **/*/some-other-file.lua`)  
3. Make a change in either file  
4. Place the cursor on the line that was changed  
5. Run `:lua require("gitsigns").preview_hunk()`

### Gitsigns debug messages

```
signs.init: Using vimfn signs                                                                                                                                                                                   
run_job: git --no-pager --literal-pathspecs --version
fn: Deriving GitSignsAdd from DiffAdd
fn: Deriving GitSignsChange from DiffChange
fn: Deriving GitSignsDelete from DiffDelete
fn: Deriving GitSignsAddNr from GitSignsAdd
fn: Deriving GitSignsChangeNr from GitSignsChange
fn: Deriving GitSignsDeleteNr from GitSignsDelete
fn: Deriving GitSignsAddLn from DiffAdd
fn: Deriving GitSignsChangeLn from DiffChange
fn: Deriving GitSignsAddPreview from DiffAdd
fn: Deriving GitSignsDeletePreview from DiffDelete
fn: Deriving GitSignsCurrentLineBlame from NonText
fn: Deriving GitSignsAddInline from TermCursor
fn: Deriving GitSignsDeleteInline from TermCursor
fn: Deriving GitSignsChangeInline from TermCursor
fn: Deriving GitSignsAddLnInline from GitSignsAddInline
fn: Deriving GitSignsChangeLnInline from GitSignsChangeInline
fn: Deriving GitSignsDeleteLnInline from GitSignsDeleteInline
fn: Deriving GitSignsAddLnVirtLn from GitSignsAddLn
fn: Deriving GitSignsChangeVirtLn from GitSignsChangeLn
fn: Deriving GitSignsDeleteVirtLn from DiffDelete
fn: Deriving GitSignsAddLnVirtLnInLine from GitSignsAddLnInline
fn: Deriving GitSignsChangeVirtLnInLine from GitSignsChangeLnInline
fn: Deriving GitSignsDeleteVirtLnInLine from GitSignsDeleteLnInline
attach(1): Attaching (trigger=setup)
run_job: git --no-pager --literal-pathspecs config user.name
run_job: git --no-pager --literal-pathspecs rev-parse --show-toplevel --absolute-git-dir --abbrev-ref HEAD
run_job: git --no-pager --literal-pathspecs --git-dir /Users/garrett/.config/.git -c core.quotepath=off ls-files --stage --others --exclude-standard --eol /Users/garrett/.config/nvim/plugin/packer.lua
watch_gitdir(1): Watching git dir
run_job: git --no-pager --literal-pathspecs --git-dir /Users/garrett/.config/.git show :0:nvim/plugin/packer.lua
update(1): updates: 1, jobs: 5
attach(6): Attaching (trigger=BufRead)
run_job: git --no-pager --literal-pathspecs config user.name
run_job: git --no-pager --literal-pathspecs rev-parse --show-toplevel --absolute-git-dir --abbrev-ref HEAD
run_job: git --no-pager --literal-pathspecs --git-dir /Users/garrett/.config/.git -c core.quotepath=off ls-files --stage --others --exclude-standard --eol /Users/garrett/.config/nvim/lua/config/gitsigns.lua
watch_gitdir(6): Watching git dir
run_job: git --no-pager --literal-pathspecs --git-dir /Users/garrett/.config/.git show :0:nvim/lua/config/gitsigns.lua
update(6): updates: 2, jobs: 9
update(6): updates: 3, jobs: 9
update(6): updates: 4, jobs: 9
Press ENTER or type command to continue
```

```
:Gitsigns dump_cache
{ {
    compare_text = { "...",
      head = "local bootstrap",
      length = 56
    },
    file = "/Users/garrett/.config/nvim/plugin/packer.lua",
    force_next_update = false,
    git_obj = {
      encoding = "utf-8",
      file = "/Users/garrett/.config/nvim/plugin/packer.lua",
      i_crlf = false,
      mode_bits = "100644",
      object_name = "4dae5e6f0e6afa4b77aa15368468130cb3ef1f86",
      relpath = "nvim/plugin/packer.lua",
      repo = {
        abbrev_head = "work",
        detached = false,
        gitdir = "/Users/garrett/.config/.git",
        toplevel = "/Users/garrett/.config",
        username = "Garrett Oreilly"
      },
      w_crlf = false
    },
    gitdir_watcher = <userdata 1>,
    hunks = {},
    staged_diffs = {}
  },
  [6] = {
    compare_text = { "...",
      head = "return {",
      length = 73
    },
    file = "/Users/garrett/.config/nvim/lua/config/gitsigns.lua",
    force_next_update = false,
    git_obj = {
      encoding = "utf-8",
      file = "/Users/garrett/.config/nvim/lua/config/gitsigns.lua",
      i_crlf = false,
      mode_bits = "100644",
      object_name = "ecdc64dd82424f2f94142ae007c59fab1f337274",
      relpath = "nvim/lua/config/gitsigns.lua",
      repo = {
        abbrev_head = "work",
        detached = false,
        gitdir = "/Users/garrett/.config/.git",
        toplevel = "/Users/garrett/.config",
        username = "Garrett Oreilly"
      },
      w_crlf = false
    },
    gitdir_watcher = <userdata 2>,
    hunks = { {
        added = {
          count = 1,
          lines = { "" },
          start = 5
        },
        head = "@@ -4 +5,1 @@",
        removed = {
          count = 0,
          lines = {},
          start = 4
        },
        type = "add",
        vend = 5
      } },
    staged_diffs = {}
  }
}
Press ENTER or type command to continue
```

**Comment by lewis6991** [comment] 2022-09-15 07:20
Duplicate of #628

**Closed** 2022-09-15 07:21 UTC
Labels: bug, duplicate
