### ISSUE TITLE
Coroutine failed attempting to index local bcache

### ISSUE THREAD

**Issue by mirosval** [lewis6991/gitsigns.nvim#153] opened 2021-04-15 06:46 UTC
**Describe the bug**

I'm getting this error somewhat regularly:
```The coroutine failed with this message: ...slav/.config/nvim/plugged/gits
igns.nvim/lua/gitsigns.lua:452: attempt to index local 'bcache' (a nil value)
```

**To Reproduce**

As far as I can tell this happens when I'm performing git operations outside of neovim. So I guess its that the git client is writing something while gitsigns is trying to reload the file or something like that.

I've added debug_mode to gitsigns, so when this happens again I will try to update with more info.

**Screenshots**
<img width="967" alt="Screenshot 2021-04-15 at 08 38 28" src="https://user-images.githubusercontent.com/1315417/114825017-f6d1e100-9dc5-11eb-8597-1c1b6fba636a.png">

**Additional context**
System: Mac 11.2.3 (20D91)
Neovim version: NVIM v0.5.0-dev+nightly-682-g8665a96b9

**Comment by lewis6991** [comment] 2021-04-15 08:13
This looks like a it's the same issue as #138.

**Comment by lewis6991** [comment] 2021-04-15 12:05
Closing this as a duplicate but I would really appreciate it if you can find a way to reproduce this. Comment on #138 if you do.

Thanks.

**Closed by lewis6991** 2021-04-15 12:05 UTC
Labels: bug, duplicate
