### ISSUE TITLE
Format string for blame_line timestamps

### ISSUE THREAD

**Issue by mrjones2014** [lewis6991/gitsigns.nvim#472] opened 2022-02-09 11:41 UTC
**Is your feature request related to a problem? Please describe.**
I'd like the timestamp in the `blame_line` popup to use 12 hour (AM/PM) time instead of 24 hour time. This could be solved by allowing me to set a custom time format string.

**Describe the solution you'd like**
Add a config option to specify the timestamp format string.

**Describe alternatives you've considered**
Forking the project, I guess? I don't think there's any way to do this without code changes.

**Additional context**
24 hour time adds mental load (a small amount, but still some). I'd like to be able to see the time in 12 hour (AM/PM) time.

**Comment by lewis6991** [comment] 2022-02-09 13:04
Duplicate of #291

**Closed by lewis6991** 2022-02-09 13:04 UTC
Labels: enhancement
