### ISSUE TITLE
Inlay-hints (virtualtext) get's seen as a diff sometimes

### ISSUE THREAD

**Issue by elkowar** [lewis6991/gitsigns.nvim#171] opened 2021-05-01 09:29 UTC
**Describe the bug**
When using virtualtext features, such as the inline hints ones provided by https://github.com/simrat39/rust-tools.nvim/,
After a save the entire file get's seen as changed for a second after saving.

**Comment by lewis6991** [comment] 2021-05-01 09:43
Sorry I don't use rust-tools. Can you provide simple steps to reproduce the issue. There are details on how to do this in the issue template.

Most likely this is caused by rust-tools.nvim messing with the buffer text. Gitsigns only does the diff on the text returned by `vim.api.nvim_buf_get_lines()` and virtual text should be excluded from that, if it isn't then that's an nvim bug.

**Comment by elkowar** [comment] 2021-05-01 10:01
ohhhhhhhh okay, after some more inspection, it doesn't seem to be related to rust-tools or the virtualtext... I'll try to set up a minimal example, or at least figure out which plugins are related to this. Main thing I noticed up until now is that if I turn on rainbow parenthesis from treesitter - in a rust document - the changed line pops up for roughly a second every time i save. If I turn if off, it pops up for ~ 100ms. In other file formats that doesn't happen. I'll try to figure out more details ^^

**Comment by lewis6991** [comment] 2021-05-03 15:57
Any updates on this?

**Comment by elkowar** [comment] 2021-05-03 16:20
Haven't yet been able to figure out what exactly this is related to. I've gone through half my plugins now to try and disable them to see if the short popup of the change-signs go away, but nothing yet. I've also been able to verify that I only notice the issue in Rust files, which still happens _after_ disabling all rust-related plugins (including anything LSP related).

**Comment by lewis6991** [comment] 2021-05-16 22:21
Closing. Please reopen if you get updates on this.

**Closed by lewis6991** 2021-05-16 22:21 UTC
Labels: bug, needs confirmation
