### ISSUE TITLE
E5108: Error executing lua ...ite/pack/packer/start/gitsigns.nvim/lua/gitsigns/git.lua:194: attempt to yield across C-call boundary

### ISSUE THREAD

**Issue by AllenDang** [lewis6991/gitsigns.nvim#354] opened 2021-09-08 05:25 UTC
### Description

This issue was originally report to `project.nvim` https://github.com/ahmedkhalf/project.nvim/issues/21 since I'm experienced it from opening project.

But I think it should related to gitsigns.

The full error message is
`E5108: Error executing lua ...k/packer/start/project.nvim/lua/project_nvim/project.lua:174: Vim(lua):E5108: Error executing lua ...ite/pack/packer/start/gitsigns.nvim/lua/gitsigns/git.lua:194: attempt to yield across C-call boundary`

### Neovim version

0.5.0

### Operating system and version

macOS 11.15

### Steps to reproduce

Repo steps:

1. Lanuch nvim.
2. Telescope projects.
3. Select any project for the first time will result at this error.
`E5108: Error executing lua ...k/packer/start/project.nvim/lua/project_nvim/project.lua:174: Vim(lua):E5108: Error executing lua ...ite/pack/packer/start/gitsigns.nvim/lua/gitsigns/git.lua:194: attempt to yield across C-call boundary`
4. Telescope projects and select same project again works normally.

### Expected behavior

Open project normally.

### Actual behavior

Error message occurred

### Minimal config

```Lua
...
```

**Comment by arg** [comment] 2021-09-08 06:12
Seems to be a duplicate of #352. There is a workaround for now: to revert to a commit earlier than https://github.com/lewis6991/gitsigns.nvim/commit/7e5a748f341eed78a0e548ad6a06bcfaa5d5cfe4

**Comment by h3ndry** [comment] 2021-09-08 06:15
> Seems to be a duplicate of #352. There is a workaround for now: to revert to a commit earlier than [7e5a748](https://github.com/lewis6991/gitsigns.nvim/commit/7e5a748f341eed78a0e548ad6a06bcfaa5d5cfe4)

I am new here, How do you do revert?

**Comment by arg** [comment] 2021-09-08 06:20
1. In shell, go to a directory where gitsigns is installed. For example, In my case (I'm using VimPlug) it would be
   ```sh
   $ cd ~/.config/nvim/plugged/gitsigns.nvim
   ```
2. Use `git checkout` to revert to some specific commit
   ```sh
   $ git checkout 25d4b182ece5b03cd4b2d8c196f3c38e0df58801
   ```
That just fixed the crash for me. Also don't forget to `git checkout master` once the issue is fixed by maintainer.

**Comment by h3ndry** [comment] 2021-09-08 06:20
I get a similar error
```Error detected while processing DirChanged Autocommands for "*":
E5108: Error executing lua ...ite/pack/packer/start/gitsigns.nvim/lua/gitsigns/git.lua:194: attempt
to yield across C-call boundary
Error detected while processing function <SNR>91_NetrwBrowseChgDir[106]..<SNR>91_NetrwOptionsRestore
:
line   84:
E171: Missing :endif
Error detected while processing function <SNR>91_NetrwBrowseChgDir:
line  106:
E171: Missing :endif
Press ENTER or type command to continue
```

**Comment by h3ndry** [comment] 2021-09-08 06:39
> ```shell
> git checkout 25d4b182ece5b03cd4b2d8c196f3c38e0df58801
> ```

Thank you so much... I manage to fix it.

**Comment by cursorzz** [comment] 2021-09-08 06:53
this seems related to the weird behavior of telescope.nvim I encounter today.

do the nornal :Telescope git_files, and select a file, <cr> does bring me the file, but the content is empty unless I have to :e to reload it.

and also got similar error for a few times. (that's why I find disable the gitsigns plugin can solve this issue)
```
gitsigns/git.lua:194: attempt to yield across C-call boundary
```



> > I am new here, How do you do revert?
> 
>     1. In shell, go to a directory where gitsigns is installed. For example, In my case (I'm using VimPlug) it would be
>        ```shell
>        $ cd ~/.config/nvim/plugged/gitsigns.nvim
>        ```
> 
>     2. Use `git checkout` to revert to some specific commit
>        ```shell
>        $ git checkout 25d4b182ece5b03cd4b2d8c196f3c38e0df58801
>        ```
> 
> 
> That just fixed the crash for me. Also don't forget to `git checkout master` and then update via your Vim plugins manager as usual, once the issue is fixed by maintainer.

btw. checkout to old commit does works for me

**Comment by lewis6991** [comment] 2021-09-08 07:58
Should be fixed in https://github.com/lewis6991/gitsigns.nvim/commit/72151be916b716c7c181cdbe53d533b28a2bc4c2

**Closed by lewis6991** 2021-09-08 07:58 UTC
Labels: bug
