### ISSUE TITLE
A lot of messages "decor_provider_invoke:47: error in provider gitsigns" in nvim log

### ISSUE THREAD

**Issue by dtcyganok** [lewis6991/gitsigns.nvim#807] opened 2023-06-05 10:57 UTC
### Description

I have quite a few error messages in my nvim log:
```log
ERR 2023-06-03T15:54:03.669 nvim.12976.0 decor_provider_invoke:47: error in provider gitsigns:win: Error executing lua: ...cal/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/hunks.lua:190: assertion failed!
stack traceback:
	[C]: in function 'assert'
	...cal/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/hunks.lua:190: in function 'calc_signs'
	...l/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/manager.lua:68: in function 'apply_win_signs0'
	...l/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/manager.lua:81: in function 'apply_win_signs'
	...l/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/manager.lua:555: in function <...l/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/manager.lua:546>
```

Can't say exactly what causes this bugs, but it's probably a `vim.api.nvim_win_set_buf` call from my configuration

### Neovim version

0.9.1

### Operating system and version

Linux (rolling)

### Expected behavior

No errors in the nvim log

### Actual behavior

See the description above

### Minimal config

```Lua
vim.o.packpath = '/tmp/nvim/site'

local plugins = {
  gitsigns = 'https://github.com/lewis6991/gitsigns.nvim',
  -- ADD OTHER PLUGINS _NECESSARY_ TO REPRODUCE THE ISSUE
}

for name, url in pairs(plugins) do
  local install_path = '/tmp/nvim/site/pack/test/start/'..name
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
end

require('gitsigns').setup{
  debug_mode = true, -- You must add this to enable debug messages
  -- ADD GITSIGNS CONFIG THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
}

-- ADD INIT.LUA SETTINGS THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
```

### Steps to reproduce

Can't say

**Comment by lewis6991** [comment] 2023-06-05 14:09
Duplicate of #802

**Closed** 2023-06-05 14:09 UTC
Labels: bug
