### ISSUE TITLE
Cache for buffer {number} was nil

### ISSUE THREAD

**Issue by kristijanhusak** [lewis6991/gitsigns.nvim#26] opened 2020-11-30 14:45 UTC
**Describe the bug**
This happened to me several times. I don't know how to reproduce it unfortunately. If I figure it out in the meantime i'll update the issue.

**To Reproduce**
Don't know unfortunately. It happened few times, randomly.

**Observed output**
I'm getting this error:
```
Error executing vim.schedule lua callback: ...pack/packager/start/gitsigns.nvim/lua/gitsigns/async.lua:21: .../nvim/pack/packager/start/gitsigns.nvim/lua/gitsigns.lua:272: Cache for buffer 6 was nil
```

**System**
Linux, latest neovim master.

**Comment by lewis6991** [comment] 2020-11-30 15:03
I've been hitting this issue too now and again, and as like you have no idea how to get it to systematically occur.

The cache is populated when we attach to the buffer and only ever cleared when we detach from the buffer. Both these events (attach and detach) are triggered via `nvim_buf_attach`. So either:
- Detach is being called multiple times for a buffer.
- The cache is being deleted for whatever reason.

**Comment by lewis6991** [comment] 2020-12-16 16:26
Can you update and see if the issue is fixed (with 6433129ce42257e20e6518a0c73ee7636b5a8b3d), I found a bug that could cause this.

**Comment by lewis6991** [comment] 2021-01-14 18:40
Closing this since no updates. Please raise a new issue if you see this again.

**Closed by lewis6991** 2021-01-14 18:40 UTC
Labels: bug

**Comment by edementyev** [comment] 2021-04-11 18:31
I'm having the same issue, it seems to appear every time I reload the buffer with :e

**Comment by lewis6991** [comment] 2021-04-11 22:48
If you can reproduce this consistently then please raise an issue with exact instructions on how it to do so.

**Comment by lewis6991** [comment] 2021-04-11 22:54
I can actually reproduced this as simply as you described (`e!<cr>u`). I'll raise an issue thanks!

**Comment by lcrockett** [comment] 2021-06-09 12:52
Any news on this issue ? I'm (randomly) hitting this same issue. I'll have to quit Neovim completely and reopen my workspace to get `gitsigns` to work properly again. I'll be happy to share whatever details might help you in trying to pinpoint this issue.

This error occurs on a Linux workstation using `NVIM v0.5.0-dev+1375-gca802046b`. Additionally, i'm doing a `Gitsigns attach` upon `BufNew,BufEnter,BufHidden,FocusGained` and a `Gitsigns detach` on `BufLeave,FocusLost` using autocommands to aid in showing Gitsigns decorations only for the currently opened buffer.

I'm also having other issues with the virtual text for the blame line, but I think it's best to address those in a separate issue.

<details>
<summary>configuration</summary>

```lua
require('gitsigns').setup {
  current_line_blame =  true,
  current_line_blame_formatter =
    function(name, blame_info)
      if blame_info.author == name then
        blame_info.author = 'You'
      end

      local text

      if blame_info.author == 'Not Committed Yet' then
        text = string.format(
          '           %s | %s | %s',
          'You',
          os.date('%Y/%m/%d %H:%M', tonumber(blame_info['author_time'])),
          'Uncommitted changes'
        )
      else
        text = string.format(
          '           %s | %s | %s | %s',
          blame_info.author,
          os.date('%Y/%m/%d %H:%M', tonumber(blame_info['author_time'])),
          blame_info.abbrev_sha,
          blame_info.summary
        )
      end

      return {{' '..text, 'GitSignsCurrentLineBlame'}}
    end,
  keymaps = {
    noremap = false,
    buffer = false,
  },
  numhl = true,
  preview_config = {
    col      = 2,
    border   = {"╭" , "─" , "╮" , "│" , "╯" , "─" , "╰", "│"},
    style    = 'minimal',
    relative = 'cursor',
    row      = 2
  },
  signs = {
    add          = {hl = 'GitSignsAdd'   , text = '│', numhl='GitSignsAdd'   , linehl='GitSignsAddLineHighlight'},
    change       = {hl = 'GitSignsChange', text = '│', numhl='GitSignsChange', linehl='GitSignsChangeLineHighlight'},
    delete       = {hl = 'GitSignsDelete', text = '_', numhl='GitSignsDelete', linehl='GitSignsDeleteLineHighlight'},
    topdelete    = {hl = 'GitSignsDelete', text = '‾', numhl='GitSignsDelete', linehl='GitSignsDeleteLineHighlight'},
    changedelete = {hl = 'GitSignsChange', text = '~', numhl='GitSignsChange', linehl='GitSignsChangeLineHighlight'},
  },
  use_decoration_api = true
}
```
</details>

![image](https://user-images.githubusercontent.com/58056722/121356474-2b2ecd00-c931-11eb-9d2e-45f8aeb06126.png)

**Comment by lewis6991** [comment] 2021-06-09 13:46
> Any news on this issue ?

The issue is closed, so not really. As far as I was aware, this is pretty much resolved.

>  I'm (randomly) hitting this same issue.

I suspect one of your plugins is creating and killing buffers very quickly. It's really the only thing that can cause this error. I know nvim-tree does this.

> Additionally, i'm doing a Gitsigns attach upon BufNew,BufEnter,BufHidden,FocusGained and a Gitsigns detach on BufLeave,FocusLost using autocommands to aid in showing Gitsigns decorations only for the currently opened buffer.

I don't think this is a good idea. This will cause gitsigns to constantly run attach/detach way too often. This could be why you are hitting that error.

> I'm also having other issues with the virtual text for the blame line, but I think it's best to address those in a separate issue.

PR's are welcome. Otherwise I'll need reproducable steps.

**Comment by lcrockett** [comment] 2021-06-09 14:02
Cheers @lewis6991, i'll try to figure out if it's trigger by a different plugin, I remember hitting this error right after opening a file using the file picker of `nvim-telescope/telescope.nvim`.

Regarding limiting Gitsigns decorations only to the currently opened buffer; would you have any recommendations on how to achieve this without constantly attaching / detaching per-buffer ?

I'll try to come up with reproducable steps regarding the git blame line virtual text.

**Comment by lewis6991** [comment] 2021-06-09 14:07
> Regarding limiting Gitsigns decorations only to the currently opened buffer; would you have any recommendations on how to achieve this without constantly attaching / detaching per-buffer ?

Maybe setting `vim.wo.signcolumn` instead? You could even hide certain highlights using `'winhighlight'`. If there are other things you want to hide it may require a feature request to make certain decorations buffer/window scoped.
