### ISSUE TITLE
Async coroutine fails

### ISSUE THREAD

**Issue by marko-cerovac** [lewis6991/gitsigns.nvim#654] opened 2022-10-21 14:29 UTC
### Description

The async coroutine fails from time to time, giving an error on startup.

### Neovim version

0.8.0

### Operating system and version

Arch linux 0.6.1

### Actual behavior

This error shows up on startup:
```
Error executing luv callback:
...e/pack/packer/start/gitsigns.nvim/lua/gitsigns/async.lua:62: The coroutine failed with this message: vim/shared.lua:0: s: expected string, got nil
stack traceback:
        [C]: in function 'error'
        vim/shared.lua: in function 'validate'
        vim/shared.lua: in function 'startswith'
        ...ite/pack/packer/start/gitsigns.nvim/lua/gitsigns/git.lua:304: in function 'set_version'
        ...im/site/pack/packer/start/gitsigns.nvim/lua/gitsigns.lua:476: in function <...im/site/pack/packer/start/gitsigns.nvim/lua/gitsigns.lua:442>
stack traceback:
        [C]: in function 'error'
        ...e/pack/packer/start/gitsigns.nvim/lua/gitsigns/async.lua:62: in function 'callback'
        ...ite/pack/packer/start/gitsigns.nvim/lua/gitsigns/git.lua:195: in function 'callback'
        ...k/packer/start/gitsigns.nvim/lua/gitsigns/subprocess.lua:74: in function <...k/packer/start/gitsigns.nvim/lua/gitsigns/subprocess.lua:59>
        [C]: in function 'cmd'
        /home/marko/.config/nvim/plugin/packer_compiled.lua:357: in function </home/marko/.config/nvim/plugin/packer_compiled.lua:10>
        [C]: in function 'pcall'
        /home/marko/.config/nvim/plugin/packer_compiled.lua:10: in main chunk
```

### Minimal config

```Lua
vim.o.packpath = '/tmp/nvim/site'

local plugins = {
  gitsigns = 'https://github.com/lewis6991/gitsigns.nvim',
  -- ADD OTHER PLUGINS _NECESSARY_ TO REPRODUCE THE ISSUE
}

for name, url in pairs(plugins) do
  local install_path = '/tmp/nvim/site/pack/test/start/'..name
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
end

require('gitsigns').setup{
  debug_mode = true, -- You must add this to enable debug messages
  -- ADD GITSIGNS CONFIG THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
}

-- ADD INIT.LUA SETTINGS THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
```

### Steps to reproduce

1. `nvim --clean -u minimal.lua`
2. ...

**Comment by lewis6991** [comment] 2022-10-21 15:12
This can only happen if `git --version` returns `nil`. You can avoid this by forcing the version in your config.

**Comment by lewis6991** [comment] 2022-10-21 15:12
Duplicate of #635

**Closed by lewis6991** 2022-10-21 15:12 UTC
Labels: bug

**Comment by marko-cerovac** [comment] 2022-10-24 23:58
@lewis6991 how would I do that exactly?
