### ISSUE TITLE
wrap=false still wraps

### ISSUE THREAD

**Issue by justinmk** [lewis6991/gitsigns.nvim#552] opened 2022-04-30 23:41 UTC
### Description

Seems like wrap=false doesn't override 'wrapscan'.

### Neovim version

0.8.0-dev 696708157974

### Operating system and version

macos

### Expected behavior

wrap=false should override 'wrapscan'.

### Actual behavior

wrap=false doesn't override 'wrapscan'.

### Minimal config

```Lua
use'lewis6991/gitsigns.nvim'
require('gitsigns').setup()
set wrapscan
```

### Steps to reproduce

1. `:set wrapscan`
2. call `next_hunk()` with wrap=false:
   ```
   lua require('gitsigns'):next_hunk({wrap=false})
   ```
3. it wraps around to the first hunk in the buffer

**Comment by lewis6991** [comment] 2022-05-01 08:51
Works for me.

I think the issue is `lua require('gitsigns'):next_hunk({wrap=false})` should be `lua require('gitsigns').next_hunk({wrap=false})`.

**Comment by justinmk** [comment] 2022-05-01 11:16
whoops, that's right! Might be worth guarding against this? This patch seems to work:

```diff
diff --git a/lua/gitsigns.lua b/lua/gitsigns.lua
index e3b59855b512..04edec8a01ec 100644
--- a/lua/gitsigns.lua
+++ b/lua/gitsigns.lua
@@ -453,7 +453,13 @@ M.setup = void(function(cfg)
 end)
 
 return setmetatable(M, {
-   __index = function(_, f)
-      return (require('gitsigns.actions'))[f]
-   end,
+   __index = function(self,f)
+      return function(...)
+         if self == ... then -- method call
+            error('method call (:) not implemented, did you mean to use dot (.)?')
+         else
+            (require('gitsigns.actions'))[f](...)
+         end
+      end
+  end
 })
```

**Comment by lewis6991** [comment] 2022-05-12 10:45
I not against doing this, but it's hard to justify as It's not really a standard convention (that I know of), and not even Neovim core guards against this.

**Comment by lewis6991** [comment] 2022-05-12 10:46
Will close the issue as the reported problem is resolved, but the guard issue is still open for discussion.

**Closed by lewis6991** 2022-05-12 10:46 UTC
Labels: bug

**Comment by justinmk** [comment] 2022-05-12 12:47
> not even Neovim core guards against this.

Nvim core probably should do so, if there is risk of confusion. In the case of gitsigns, almost everything seemed to work, which is quite confusing.

**Comment by lewis6991** [comment] 2022-05-12 15:32
There is no validation or arity checks to gitsigns actions, so any action that takes no arguments or a table as its first argument won't complain if it is called as a method.

So maybe the actual solution here is to just validate the arguments.
