### ISSUE TITLE
Intermitent Error Async Routine failed

### ISSUE THREAD

**Issue by uwla** [lewis6991/gitsigns.nvim#1149] opened 2024-11-26 13:13 UTC
### Description

Sometimes I get this error right after starting NeoVim:

```
Error executing luv callback:
...cal/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/async.lua:95: The async coroutine failed: .../share/nvim/lazy/gitsigns.nvim/lua/gitsigns/git/repo.lua:145: table index is nil
stack traceback:
	.../share/nvim/lazy/gitsigns.nvim/lua/gitsigns/git/repo.lua: in function 'get'
	...local/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/git.lua:408: in function 'new'
	...al/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/attach.lua:281: in function 'fn'
	.../share/nvim/lazy/gitsigns.nvim/lua/gitsigns/debounce.lua:68: in function 'attach_throttled'
	...al/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/attach.lua:432: in function <...al/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/attach.lua:431>
stack traceback:
	[C]: in function 'error'
	...cal/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/async.lua:95: in function 'cb'
	...cal/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/async.lua:145: in function 'on_exit'
	/usr/share/nvim/runtime/lua/vim/_system.lua:300: in function </usr/share/nvim/runtime/lua/vim/_system.lua:270>
```

This happens both at git and non-git codebases.

### Neovim version

NVIM v0.10.2 Build type: RelWithDebInfo LuaJIT 2.1.1727870382 Run "nvim -V1 -v" for more info

### Operating system and version

ArchLinux

### Expected behavior

The error should not happen.

### Actual behavior

I got this large red error message sometimes.

### Minimal config

```Lua
I have no ideia how to reproduce it...
It just happens sometimes.
```

### Steps to reproduce

Open a repo with Gitsigns and pray for the error to happen.
I'd say it happens 20% of the time.

**Comment by TiesDO** [comment] 2024-11-27 15:11
same error for me, but I occasionally get the following error as well after saving a file:

```
Error detected while processing BufWritePost Autocommands for "*":
Error executing lua callback: ...e/pack/packer/start/gitsigns.nvim/lua/gitsigns/async.lua:172: attempt to perform arithmetic on upvalue 'argc' (a function value
)
stack traceback:
        ...e/pack/packer/start/gitsigns.nvim/lua/gitsigns/async.lua:172: in function 'attach'
        ...im/site/pack/packer/start/gitsigns.nvim/lua/gitsigns.lua:125: in function <...im/site/pack/packer/start/gitsigns.nvim/lua/gitsigns.lua:124>
```

I'll update once I figure out how to reproduce it.

**Comment by sazk07** [comment] 2024-11-28 11:51
I am also getting this error stack on neovim nightly on Arch linux. This is the same bug as #1134

**Comment by lewis6991** [comment] 2024-11-28 11:58
Please refrain from "me too" comments unless you have useful information to progress the issue.

**Comment by lewis6991** [comment] 2024-12-04 10:23
duplicate of #1134

**Closed by lewis6991** 2024-12-04 10:23 UTC
Labels: bug
