### ISSUE TITLE
Crashing neovim: LuaJIT ASSERT lj_ccallback.c:540:

### ISSUE THREAD

**Issue by ofrades** [lewis6991/gitsigns.nvim#191] opened 2021-05-14 16:18 UTC
With latest build and latest gitsigns when I go to insert mode and type neovim crashes and I get this errors:

`LuaJIT ASSERT lj_ccallback.c:540: callback_conv_args: tvisfunc((((MSize)(((int32_t)slot)) < (MSize)((cts->miscmap))->asize) ? (&(((TValue *)(void *)(((cts->miscmap))->array).ptr64))[(((int32_t)slot))]) : lj_tab_getinth((cts->miscmap), ((int32_t)slot))))`

`fish: Job 1, “nvim . $argv” terminated by signal SIGABRT (Abort)`

**Comment by lewis6991** [comment] 2021-05-14 16:20
You need to provide more information about what your running. The latest build works fine for me and also passed CI so there is something more specific going on.

**Comment by ofrades** [comment] 2021-05-14 16:27
Terminal: kitty
Shell: fish 3.1.2 
OS: Pop!_OS 20.10 x86_64
NVIM v0.5.0-dev+1319-g7c9569702
LuaJIT 2.1.0-beta3

**Comment by lewis6991** [comment] 2021-05-14 16:31
What about if you set `config.use_internal_diff=false`?

**Comment by ofrades** [comment] 2021-05-14 16:34
> ``?

That fixes it, thanks @lewis6991

**Comment by lewis6991** [comment] 2021-05-14 16:35
Let's keep the issue open. There may be other people this affects.

**Comment by bigjazzsound** [comment] 2021-05-14 17:27
I am also getting same error. Setting use_internal_diff=false fixes the issue.

My setup is very similar to OP. Same nvim and luajit versions:

```
Terminal: alacritty
Shell: zsh 5.8 (x86_64-ubuntu-linux-gnu)
OS: Ubuntu 20.10 x86_64
NVIM v0.5.0-dev+1319-g7c9569702
LuaJIT 2.1.0-beta3
```

If there is any more info I can provide to help, let me know.

**Comment by lewis6991** [comment] 2021-05-14 17:54
How did you install neovim? Was it direct from the repo or did you use something like brew?

**Comment by bigjazzsound** [comment] 2021-05-14 17:58
I clone the neovim master branch and run `make nvim CMAKE_BUILD_TYPE=Release CMAKE_INSTALL_PREFIX=$HOME/.local && make install`

**Comment by sunjon** [comment] 2021-05-14 18:02
Experiencing the same issue here.

```
OS: Arch linux
NVIM v0.5.0-dev+1314-g7b0edaac5
LuaJIT 2.1.0-beta3
```

Nvim compiled from master a few days ago.
Editing a document results in the crash message mentioned in the OP.

**Comment by lewis6991** [comment] 2021-05-14 18:07
Is it reproducible with a minimal config?

**Comment by bigjazzsound** [comment] 2021-05-14 18:29
I am not able to recreate the issue with a minimal config.

```lua
-- Install packer outside of nvim

require "packer".startup {
  function(use)
    use {
      "wbthomason/packer.nvim",
      opt = true,
    }

    use {
      "lewis6991/gitsigns.nvim",
      requires = {
        "nvim-lua/plenary.nvim",
      },
      config = function()
        require "gitsigns".setup {
          numhl = true,
        }
      end,
    }
  end
}
```

Using the above config and editing a file does result in a crash.

**Comment by lewis6991** [comment] 2021-05-14 18:32
Is `numhl=true` needed?

**Comment by bigjazzsound** [comment] 2021-05-14 18:38
Sorry, I forgot to remove that from my original config.

I removed it and tested again. I am still not able to reproduce with the minimal config.

**Comment by lewis6991** [comment] 2021-05-14 18:48
I'm confused. Does minimal config + plenary + gitsigns cause a crash?

**Comment by bigjazzsound** [comment] 2021-05-14 18:54
minimal config + plenary + gitsigns does not cause a crash.

**Comment by lewis6991** [comment] 2021-05-14 18:58
Make sure to try a couple of edits and maybe open a file or 2 with the minimal config as the issue is related to FFI variable recycling.

**Comment by sunjon** [comment] 2021-05-14 19:53
```
  {"wbthomason/packer.nvim"},
  {"nvim-lua/plenary.nvim"},
  {"nvim-lua/popup.nvim"},

  {
    "lewis6991/gitsigns.nvim",
    config = conf "gitsigns"
  },
  {
    "nvim-lua/telescope.nvim",
    config = conf "telescope",
    requires = {
      {"nvim-telescope/telescope-fzf-native.nvim", run = "make"},
    },
  },
```
After bisecting my config, the above is as minimal as I can get it to have a guaranteed crash. 
I think I encountered one other permutation that can also cause a crash; That too was when another plugin/extension was using FFI (they're not that common I guess).

**Comment by lewis6991** [comment] 2021-05-14 20:00
Thanks for digging further. I noticed @bigjazzsound has `telescope-fzf-native.nvim` too so you both have that in common.

What does your telescope config contain?

**Comment by lewis6991** [comment] 2021-05-14 20:08
This is probably nothing but I noticed this in `telescope-fzf-native.nvim`:

```lua

fzf.get_pos = function(input, pattern_struct, slab)
  local text = ffi.new("char[?]", #input + 1)
  ffi.copy(text, input)
  local pos = native.get_positions(text, pattern_struct, slab)
  local res = {}
  local i = 1
  local add_cb = ffi.cast("handle_position", function(v)
    res[i] = tonumber(v) + 1
    i = i + 1;
  end)
  native.iter_positions(pos, add_cb)
  native.free_positions(pos)
  add_cb:free()

  return res
end
```

Which isn't running has a ffi-lua callback but doesn't have `jit.off()` so this will be suseptible to PANIC crashes like gitsigns did.

The whole point of the change that introduced this issue was to disable the jit compiler when doing FFI as that was causing a different crash for other users.

**Comment by ofrades** [comment] 2021-05-14 20:12
@lewis6991 I also have telescope-fzf-native

**Comment by bigjazzsound** [comment] 2021-05-14 20:12
I did some tests and found that:

* Disabling `telescope-fzf-native.nvim` no longer makes neovim crash
* Rolling back gitsigns to d57f445297373440788faf54b2e325eda0df063a also fixes the issue

**Comment by lewis6991** [comment] 2021-05-14 20:19
Ok so we have narrowed this down somewhat. This also gives me some confidence that the gitsigns change is probably ok and has just exposed a lurking issue somewhere.

I've installed `telescope-fzf-native.nvim` myself and appears to be working but can't seem to generate the crash.

**Comment by clason** [comment] 2021-05-14 20:22
Just to add a single data point: I cannot reproduce either with a (non-minimal) config including gitsigns and fzf-native. (This is macOS on Intel; I suspect this is platform-dependent.)

**Comment by lewis6991** [comment] 2021-05-14 20:30
Good point, I'll see if I can reproduce on Linux.

**Comment by Conni2461** [comment] 2021-05-14 20:40
I still get a crash when i reduce all my fzf-native code to `ffi.load` libfzf.so and open a file with edit. And i also still get a crash if i do `jit.off(true, true)`

**Comment by lewis6991** [comment] 2021-05-14 20:42
@Conni2461 : Can you hack that `lua/gitsigns/diff.lua` too? And if you can, revert parts of the commit by hand to see when the problem begins/goes away.

All the change does is recycle FFI objects instead of recreating them on every call.

**Comment by Conni2461** [comment] 2021-05-14 20:54
Sure i will look into it

**Comment by lewis6991** [comment] 2021-05-14 20:59
@Conni2461 thanks a lot. This [luajit issue](https://github.com/LuaJIT/LuaJIT/issues/699) might be helpful to understand exactly what's changed.

**Comment by lewis6991** [comment] 2021-05-14 21:02
Also just noticed a potential mistake in the change. This might help:

```diff
diff --git a/lua/gitsigns/diff.lua b/lua/gitsigns/diff.lua
index 41d011f..b1493dd 100644
--- a/lua/gitsigns/diff.lua
+++ b/lua/gitsigns/diff.lua
@@ -110,7 +110,7 @@ local hunk_results = {}

 local mmba = ffi.new('mmbuffer_t')
 local mmbb = ffi.new('mmbuffer_t')
-local xpparam = ffi.new('xpparam_t')
+local xpparam = ffi.new('xpparam_t', 1)
 local emitconf = ffi.new('xdemitconf_t')
 local emitcb = ffi.new('xdemitcb_t')

diff --git a/teal/gitsigns/diff.tl b/teal/gitsigns/diff.tl
index 1c292fa..cfd94d7 100644
--- a/teal/gitsigns/diff.tl
+++ b/teal/gitsigns/diff.tl
@@ -110,7 +110,7 @@ local hunk_results: {DiffResult} = {}

 local mmba = ffi.new('mmbuffer_t') as MMBuffer
 local mmbb = ffi.new('mmbuffer_t') as MMBuffer
-local xpparam = ffi.new('xpparam_t') as XPParam
+local xpparam = ffi.new('xpparam_t', 1) as XPParam
 local emitconf = ffi.new('xdemitconf_t') as XDEmitConf
 local emitcb = ffi.new('xdemitcb_t') as any
```

**Comment by Conni2461** [comment] 2021-05-14 21:08
doesn't seem to help

**Comment by Conni2461** [comment] 2021-05-14 21:16
Got it working again:
```diff
diff --git a/lua/gitsigns/diff.lua b/lua/gitsigns/diff.lua
index 41d011f..577105e 100644
--- a/lua/gitsigns/diff.lua
+++ b/lua/gitsigns/diff.lua
@@ -110,38 +110,37 @@ local hunk_results = {}
 
 local mmba = ffi.new('mmbuffer_t')
 local mmbb = ffi.new('mmbuffer_t')
-local xpparam = ffi.new('xpparam_t')
-local emitconf = ffi.new('xdemitconf_t')
+local xpparam = ffi.new('xpparam_t', 1)
 local emitcb = ffi.new('xdemitcb_t')
 
-local hunk_func = ffi.cast('xdl_emit_hunk_consume_func_t', function(
-   start_a, count_a, start_b, count_b)
 
-   local ca = tonumber(count_a)
-   local cb = tonumber(count_b)
-   local sa = tonumber(start_a)
-   local sb = tonumber(start_b)
+local function run_diff_xdl(fa, fb, diff_algo)
+   mmba.ptr, mmba.size = setup_mmbuffer(fa)
+   mmbb.ptr, mmbb.size = setup_mmbuffer(fb)
+   xpparam.flags = get_xpparam_flag(diff_algo)
+   local hunk_results = {}
 
+   local emitconf = ffi.new('xdemitconf_t')
+   local hunk_func = ffi.cast('xdl_emit_hunk_consume_func_t', function(
+      start_a, count_a, start_b, count_b)
 
+      local ca = tonumber(count_a)
+      local cb = tonumber(count_b)
+      local sa = tonumber(start_a)
+      local sb = tonumber(start_b)
 
-   if ca > 0 then sa = sa + 1 end
-   if cb > 0 then sb = sb + 1 end
 
-   hunk_results[#hunk_results + 1] = { sa, ca, sb, cb }
-   return 0
-end)
 
-emitconf.hunk_func = hunk_func
+      if ca > 0 then sa = sa + 1 end
+      if cb > 0 then sb = sb + 1 end
 
-local function run_diff_xdl(fa, fb, diff_algo)
-   mmba.ptr, mmba.size = setup_mmbuffer(fa)
-   mmbb.ptr, mmbb.size = setup_mmbuffer(fb)
-   xpparam.flags = get_xpparam_flag(diff_algo)
-   hunk_results = {}
+      hunk_results[#hunk_results + 1] = { sa, ca, sb, cb }
+      return 0
+   end)
+
+   emitconf.hunk_func = hunk_func
    local ok = ffi.C.xdl_diff(mmba, mmbb, xpparam, emitconf, emitcb)
-   local results = hunk_results
-   hunk_results = {}
-   return ok == 0 and results
+   return ok == 0 and hunk_results
 end
 
 jit.off(run_diff_xdl)
```

**Comment by lewis6991** [comment] 2021-05-14 21:18
Very nice. 

However the hunk_func is the one thing we want to recycle, otherwise you need to add `hunk_func:free()` to make sure it gets garbage collected.

**Comment by Conni2461** [comment] 2021-05-14 21:19
Yeah i know we want. Just missed that. I only tested for a segfault :rofl:

**Comment by Conni2461** [comment] 2021-05-14 21:21
Btw this is the backtrace of the segfault: 
![image](https://user-images.githubusercontent.com/15233006/118332747-dc953b00-b50a-11eb-95aa-c327472a43f2.png)

Do you want a coredump? Do we want to ping mike, maybe its a bug in the linux version. If he actually suggested it and his version seems to be way clearer

**Comment by lewis6991** [comment] 2021-05-14 21:38
Can you build neovim with luajit master? I know easier said than done but he probably won't care if we're not using master. Would also be great if you could condence this down to a single lua file. Then repro steps would be:

- build neovim
- make fzf native
- run this lua file

**Comment by clason** [comment] 2021-05-14 21:42
@ofrades tried with https://github.com/neovim/neovim/pull/13741 which includes Mike Pall's changes up to January at least, and could reproduce the segfault. There are newer ones on https://github.com/LuaJIT/LuaJIT/commits/v2.1, but that might help narrow things down a bit?

**Comment by Conni2461** [comment] 2021-05-14 21:46
I already builded against current master (after sending my last message) and could still reproduce this issue. Its already late for me, so i will document the reproduce steps tomorrow.

**Comment by lewis6991** [comment] 2021-05-14 21:48
No problem, thanks so much @Conni2461 for everything you've done tonight. We can continue to dig into this but I'll put up a PR to make `hunk_func` a closure again to avoid the issue for everyone else.

**Comment by Conni2461** [comment] 2021-05-14 21:49
Also there is a good chance that i do something stupid in the fzf code that causes this issues. I am not that good in c :rofl:

**Comment by lewis6991** [comment] 2021-05-14 21:53
Can anyone interested give #192 a spin which should hopefully resolve this for now.

**Comment by sunjon** [comment] 2021-05-14 21:57
> Can anyone interested give #192 a spin which should hopefully resolve this for now.

Works for me.

**Comment by Conni2461** [comment] 2021-05-15 09:21
There is something really weird going on. I am currently doing a long due refactor and try to figure out whats wrong.

One thing i noticed is that if i compile with `-Og` (for debugging purpose) the segfault doesn't happen but as soon as i compile with `-Ofast` i run into this error. (Compiler doesn't matter here. Same behavior for both gcc and clang)

I am pretty sure i am doing something wrong. I hope i can find it this weekend. I will keep you up to date @lewis6991. Hopefully you can revert the revert again and we can all benefit from that optimization :)

**Comment by lewis6991** [comment] 2021-05-15 09:26
Thanks for the update. 

To clarify, do you mean for the compilation of fzf-native or neovim?

> One thing i noticed is that if i compile with -Og (for debugging purpose) the segfault doesn't happen but as soon as i compile with -Ofast i run into this error. (Compiler doesn't matter here. Same behavior for both gcc and clang)

It's likely the issue exists in both cases but is only observable in one. This still sounds like a luajit issue to me.

**Comment by Conni2461** [comment] 2021-05-15 09:27
I meant compiling fzf-native. (neovim is compiled with Debug)

**Comment by Conni2461** [comment] 2021-05-15 10:11
Found it. Its `-ffast-math`. Compiling with `-O3` works and my benchmark returns me the same because i don't even have float point calculations in my library.

I will change that for me and we should ask someone else to verify. After that i am pretty sure you can revert :)

I will look into it more and try to find a minimal reproduce that we can report back to mike pall. Now that it doesn't affect users anymore i will take more time thought :rofl:

**Comment by clason** [comment] 2021-05-15 10:25
Possibly related: https://github.com/LuaJIT/LuaJIT/issues/448 ?

**Comment by lewis6991** [comment] 2021-05-15 10:59
>  I will change that for me and we should ask someone else to verify. After that i am pretty sure you can revert :)

I'll revert eventually. I've got some interesting changes in mind (unrelated to this) so want to get things in as stable state as possible so I can release a `v0.1`.

My main goal with these FFI changes was just to resolve the `PANIC (bad callback)` issue which should hopefully be fixed now. Once I get confirmation from users after a week or so of use I'll do a release.

> I will look into it more and try to find a minimal reproduce that we can report back to mike pall. Now that it doesn't affect users anymore i will take more time thought 🤣

That'll be great. I'm setting up a linux VM on my old intel Macbook now in hope I can reproduce the issue. It's pretty weird that re-using a callback function causes this.

**Comment by lewis6991** [comment] 2021-05-15 14:52
Got an unprompted follow up comment from Mike on https://github.com/LuaJIT/LuaJIT/issues/699:

> Sigh. You're worsening this with every try. Please give someone else a chance to fix this, who knows more about Lua and C and the FFI.
>
> And, no, please don't ask here.

Kind of rude but I was prepared for something like this since he has lots of comments like this on the issue tracker.

I double checked my original [patch](https://github.com/lewis6991/gitsigns.nvim/blob/2ad4662857215b022392fef24efb960fb0c183d1/teal/gitsigns/diff.tl) to try and figure why he replied like this and noticed a couple of things.

- The `hunk_func` is missing a 5th unused argument. This would correlate somewhat to the error message and backtrace.
- In his untested solution he reinitialises the results table before the diff and nils after. Not sure what effect this would have as opposed to just clearing before each diff but he would have done it that way for a reason.

I've raised #194 with these changes. @Conni2461 can you give this a go with the old version of `telescope-fzf-native`?

I was unable to recreate the issue on a ubuntu VM. Maybe the issue is sensitive to what version of `libc` nvim is built against. I've been using the versions `homebrew` provides.

**Comment by Conni2461** [comment] 2021-05-15 18:47
If i re-enable `-ffast-math` the error reappears for #194

**Comment by lewis6991** [comment] 2021-05-15 18:49
Dam, same backtrace?

**Comment by Conni2461** [comment] 2021-05-15 18:54
yep

**Comment by lewis6991** [comment] 2021-05-16 19:11
Going to close this since even though the issue may still be present, it doesn't seem to be observable. Though this is tightly on my radar so if anyone notices any more FFI related errors, please reopen this or open a new issue.

**Closed by lewis6991** 2021-05-16 19:11 UTC
Labels: bug, unable to reproduce
