### ISSUE TITLE
Hunks are not applied using .gitattribute filters

### ISSUE THREAD

**Issue by knpwrs** [lewis6991/gitsigns.nvim#859] opened 2023-08-22 15:33 UTC
### Description

I was editing a file that I have encrypted with https://github.com/elasticdog/transcrypt. I staged the hunk that I edited using gitsigns.nvim, and then when I went to commit I got the following error from the transcrypt precommit hook:

```
Transcrypt managed file is not encrypted in the Git index: <edited file path redacted>

You probably staged this file using a tool that does not apply .gitattribute filters as required by Transcrypt.

Fix this by re-staging the file with a compatible tool or with Git on the command line:

    git rm --cached -- <edited file path redacted>
    git add <edited file path redacted>
```

### Neovim version

v0.9.1

### Operating system and version

macOS Ventura 13.4

### Expected behavior

I should be able to stage hunks in files that use git attribute filters.

### Actual behavior

Plain text is written directly to the git index? I'm not sure how exactly to debug further. Does gitsigns.nvim use the git cli directly?

### Minimal config

```Lua
for name, url in pairs{
  gitsigns = 'https://github.com/lewis6991/gitsigns.nvim',
  -- ADD OTHER PLUGINS _NECESSARY_ TO REPRODUCE THE ISSUE
} do
  local install_path = vim.fn.fnamemodify('gitsigns_issue/'..name, ':p')
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
  vim.opt.runtimepath:append(install_path)
end

require('gitsigns').setup{
  debug_mode = true, -- You must add this to enable debug messages
  -- ADD GITSIGNS CONFIG THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
}

-- ADD INIT.LUA SETTINGS THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
```

### Steps to reproduce

1. Set up a repository with git attribute filters (git lfs, transcrypt, etc)
2. Commit a file outside of nvim
3. Attempt to stage a hunk from gitsigns.nvim
4. Observe error from transcrypt precommit hook

**Comment by lewis6991** [comment] 2023-08-22 15:35
Duplicate of #480

**Closed by lewis6991** 2023-08-22 15:35 UTC
Labels: bug
